/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppProgressoRouteImport } from './routes/_app/progresso'
import { Route as AppTreinoIndexRouteImport } from './routes/_app/treino/index'
import { Route as AppTreinoFechamentoRouteImport } from './routes/_app/treino/fechamento'
import { Route as AppTreinoHistoricoRouteImport } from './routes/_app/treino/historico'
import { Route as AppTreinoSessaoRouteImport } from './routes/_app/treino/sessao'
import { Route as AppTreinoBibliotecaIndexRouteImport } from './routes/_app/treino/biblioteca/index'
import { Route as AppTreinoBibliotecaTemplateIdRouteImport } from './routes/_app/treino/biblioteca/$templateId'
import { Route as AppTreinoHistoricoResumoRouteImport } from './routes/_app/treino/historico/resumo'
import { Route as AppTreinoHistoricoSessoesRouteImport } from './routes/_app/treino/historico/sessoes'
import { Route as AppTreinoProgramasIndexRouteImport } from './routes/_app/treino/programas/index'
import { Route as AppTreinoWarmupTemplateIdRouteImport } from './routes/_app/treino/warmup/$templateId'
import { Route as AppTreinoProgramasTreinoTemplateIdRouteImport } from './routes/_app/treino/programas/treino/$templateId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoIndexRoute = AppTreinoIndexRouteImport.update({
  id: '/treino/',
  path: '/treino/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoFechamentoRoute = AppTreinoFechamentoRouteImport.update({
  id: '/treino/fechamento',
  path: '/treino/fechamento',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoHistoricoRoute = AppTreinoHistoricoRouteImport.update({
  id: '/treino/historico',
  path: '/treino/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoSessaoRoute = AppTreinoSessaoRouteImport.update({
  id: '/treino/sessao',
  path: '/treino/sessao',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoBibliotecaIndexRoute =
  AppTreinoBibliotecaIndexRouteImport.update({
    id: '/treino/biblioteca/',
    path: '/treino/biblioteca/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTreinoBibliotecaTemplateIdRoute =
  AppTreinoBibliotecaTemplateIdRouteImport.update({
    id: '/treino/biblioteca/$templateId',
    path: '/treino/biblioteca/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTreinoHistoricoResumoRoute =
  AppTreinoHistoricoResumoRouteImport.update({
    id: '/resumo',
    path: '/resumo',
    getParentRoute: () => AppTreinoHistoricoRoute,
  } as any)
const AppTreinoHistoricoSessoesRoute =
  AppTreinoHistoricoSessoesRouteImport.update({
    id: '/sessoes',
    path: '/sessoes',
    getParentRoute: () => AppTreinoHistoricoRoute,
  } as any)
const AppTreinoProgramasIndexRoute = AppTreinoProgramasIndexRouteImport.update({
  id: '/treino/programas/',
  path: '/treino/programas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoWarmupTemplateIdRoute =
  AppTreinoWarmupTemplateIdRouteImport.update({
    id: '/treino/warmup/$templateId',
    path: '/treino/warmup/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTreinoProgramasTreinoTemplateIdRoute =
  AppTreinoProgramasTreinoTemplateIdRouteImport.update({
    id: '/treino/programas/treino/$templateId',
    path: '/treino/programas/treino/$templateId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/perfil': typeof AppPerfilRoute
  '/progresso': typeof AppProgressoRoute
  '/treino/fechamento': typeof AppTreinoFechamentoRoute
  '/treino/historico': typeof AppTreinoHistoricoRouteWithChildren
  '/treino/sessao': typeof AppTreinoSessaoRoute
  '/treino/': typeof AppTreinoIndexRoute
  '/treino/biblioteca/$templateId': typeof AppTreinoBibliotecaTemplateIdRoute
  '/treino/historico/resumo': typeof AppTreinoHistoricoResumoRoute
  '/treino/historico/sessoes': typeof AppTreinoHistoricoSessoesRoute
  '/treino/warmup/$templateId': typeof AppTreinoWarmupTemplateIdRoute
  '/treino/biblioteca/': typeof AppTreinoBibliotecaIndexRoute
  '/treino/programas/': typeof AppTreinoProgramasIndexRoute
  '/treino/programas/treino/$templateId': typeof AppTreinoProgramasTreinoTemplateIdRoute
}
export interface FileRoutesByTo {
  '/perfil': typeof AppPerfilRoute
  '/progresso': typeof AppProgressoRoute
  '/': typeof AppIndexRoute
  '/treino/fechamento': typeof AppTreinoFechamentoRoute
  '/treino/historico': typeof AppTreinoHistoricoRouteWithChildren
  '/treino/sessao': typeof AppTreinoSessaoRoute
  '/treino': typeof AppTreinoIndexRoute
  '/treino/biblioteca/$templateId': typeof AppTreinoBibliotecaTemplateIdRoute
  '/treino/historico/resumo': typeof AppTreinoHistoricoResumoRoute
  '/treino/historico/sessoes': typeof AppTreinoHistoricoSessoesRoute
  '/treino/warmup/$templateId': typeof AppTreinoWarmupTemplateIdRoute
  '/treino/biblioteca': typeof AppTreinoBibliotecaIndexRoute
  '/treino/programas': typeof AppTreinoProgramasIndexRoute
  '/treino/programas/treino/$templateId': typeof AppTreinoProgramasTreinoTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/progresso': typeof AppProgressoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/treino/fechamento': typeof AppTreinoFechamentoRoute
  '/_app/treino/historico': typeof AppTreinoHistoricoRouteWithChildren
  '/_app/treino/sessao': typeof AppTreinoSessaoRoute
  '/_app/treino/': typeof AppTreinoIndexRoute
  '/_app/treino/biblioteca/$templateId': typeof AppTreinoBibliotecaTemplateIdRoute
  '/_app/treino/historico/resumo': typeof AppTreinoHistoricoResumoRoute
  '/_app/treino/historico/sessoes': typeof AppTreinoHistoricoSessoesRoute
  '/_app/treino/warmup/$templateId': typeof AppTreinoWarmupTemplateIdRoute
  '/_app/treino/biblioteca/': typeof AppTreinoBibliotecaIndexRoute
  '/_app/treino/programas/': typeof AppTreinoProgramasIndexRoute
  '/_app/treino/programas/treino/$templateId': typeof AppTreinoProgramasTreinoTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/perfil'
    | '/progresso'
    | '/treino/fechamento'
    | '/treino/historico'
    | '/treino/sessao'
    | '/treino/'
    | '/treino/biblioteca/$templateId'
    | '/treino/historico/resumo'
    | '/treino/historico/sessoes'
    | '/treino/warmup/$templateId'
    | '/treino/biblioteca/'
    | '/treino/programas/'
    | '/treino/programas/treino/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/perfil'
    | '/progresso'
    | '/'
    | '/treino/fechamento'
    | '/treino/historico'
    | '/treino/sessao'
    | '/treino'
    | '/treino/biblioteca/$templateId'
    | '/treino/historico/resumo'
    | '/treino/historico/sessoes'
    | '/treino/warmup/$templateId'
    | '/treino/biblioteca'
    | '/treino/programas'
    | '/treino/programas/treino/$templateId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/perfil'
    | '/_app/progresso'
    | '/_app/'
    | '/_app/treino/fechamento'
    | '/_app/treino/historico'
    | '/_app/treino/sessao'
    | '/_app/treino/'
    | '/_app/treino/biblioteca/$templateId'
    | '/_app/treino/historico/resumo'
    | '/_app/treino/historico/sessoes'
    | '/_app/treino/warmup/$templateId'
    | '/_app/treino/biblioteca/'
    | '/_app/treino/programas/'
    | '/_app/treino/programas/treino/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progresso': {
      id: '/_app/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/': {
      id: '/_app/treino/'
      path: '/treino'
      fullPath: '/treino/'
      preLoaderRoute: typeof AppTreinoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/fechamento': {
      id: '/_app/treino/fechamento'
      path: '/treino/fechamento'
      fullPath: '/treino/fechamento'
      preLoaderRoute: typeof AppTreinoFechamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/historico': {
      id: '/_app/treino/historico'
      path: '/treino/historico'
      fullPath: '/treino/historico'
      preLoaderRoute: typeof AppTreinoHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/sessao': {
      id: '/_app/treino/sessao'
      path: '/treino/sessao'
      fullPath: '/treino/sessao'
      preLoaderRoute: typeof AppTreinoSessaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/biblioteca/': {
      id: '/_app/treino/biblioteca/'
      path: '/treino/biblioteca'
      fullPath: '/treino/biblioteca/'
      preLoaderRoute: typeof AppTreinoBibliotecaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/biblioteca/$templateId': {
      id: '/_app/treino/biblioteca/$templateId'
      path: '/treino/biblioteca/$templateId'
      fullPath: '/treino/biblioteca/$templateId'
      preLoaderRoute: typeof AppTreinoBibliotecaTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/historico/resumo': {
      id: '/_app/treino/historico/resumo'
      path: '/resumo'
      fullPath: '/treino/historico/resumo'
      preLoaderRoute: typeof AppTreinoHistoricoResumoRouteImport
      parentRoute: typeof AppTreinoHistoricoRoute
    }
    '/_app/treino/historico/sessoes': {
      id: '/_app/treino/historico/sessoes'
      path: '/sessoes'
      fullPath: '/treino/historico/sessoes'
      preLoaderRoute: typeof AppTreinoHistoricoSessoesRouteImport
      parentRoute: typeof AppTreinoHistoricoRoute
    }
    '/_app/treino/programas/': {
      id: '/_app/treino/programas/'
      path: '/treino/programas'
      fullPath: '/treino/programas/'
      preLoaderRoute: typeof AppTreinoProgramasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/warmup/$templateId': {
      id: '/_app/treino/warmup/$templateId'
      path: '/treino/warmup/$templateId'
      fullPath: '/treino/warmup/$templateId'
      preLoaderRoute: typeof AppTreinoWarmupTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treino/programas/treino/$templateId': {
      id: '/_app/treino/programas/treino/$templateId'
      path: '/treino/programas/treino/$templateId'
      fullPath: '/treino/programas/treino/$templateId'
      preLoaderRoute: typeof AppTreinoProgramasTreinoTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTreinoHistoricoRouteChildren {
  AppTreinoHistoricoResumoRoute: typeof AppTreinoHistoricoResumoRoute
  AppTreinoHistoricoSessoesRoute: typeof AppTreinoHistoricoSessoesRoute
}

const AppTreinoHistoricoRouteChildren: AppTreinoHistoricoRouteChildren = {
  AppTreinoHistoricoResumoRoute: AppTreinoHistoricoResumoRoute,
  AppTreinoHistoricoSessoesRoute: AppTreinoHistoricoSessoesRoute,
}

const AppTreinoHistoricoRouteWithChildren =
  AppTreinoHistoricoRoute._addFileChildren(AppTreinoHistoricoRouteChildren)

interface AppRouteChildren {
  AppPerfilRoute: typeof AppPerfilRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTreinoFechamentoRoute: typeof AppTreinoFechamentoRoute
  AppTreinoHistoricoRoute: typeof AppTreinoHistoricoRouteWithChildren
  AppTreinoSessaoRoute: typeof AppTreinoSessaoRoute
  AppTreinoIndexRoute: typeof AppTreinoIndexRoute
  AppTreinoBibliotecaTemplateIdRoute: typeof AppTreinoBibliotecaTemplateIdRoute
  AppTreinoWarmupTemplateIdRoute: typeof AppTreinoWarmupTemplateIdRoute
  AppTreinoBibliotecaIndexRoute: typeof AppTreinoBibliotecaIndexRoute
  AppTreinoProgramasIndexRoute: typeof AppTreinoProgramasIndexRoute
  AppTreinoProgramasTreinoTemplateIdRoute: typeof AppTreinoProgramasTreinoTemplateIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPerfilRoute: AppPerfilRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppIndexRoute: AppIndexRoute,
  AppTreinoFechamentoRoute: AppTreinoFechamentoRoute,
  AppTreinoHistoricoRoute: AppTreinoHistoricoRouteWithChildren,
  AppTreinoSessaoRoute: AppTreinoSessaoRoute,
  AppTreinoIndexRoute: AppTreinoIndexRoute,
  AppTreinoBibliotecaTemplateIdRoute: AppTreinoBibliotecaTemplateIdRoute,
  AppTreinoWarmupTemplateIdRoute: AppTreinoWarmupTemplateIdRoute,
  AppTreinoBibliotecaIndexRoute: AppTreinoBibliotecaIndexRoute,
  AppTreinoProgramasIndexRoute: AppTreinoProgramasIndexRoute,
  AppTreinoProgramasTreinoTemplateIdRoute:
    AppTreinoProgramasTreinoTemplateIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
